import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { afterEach, describe, expect, it, vi } from "vitest";

import { parseFlightFile } from "@/lib/flightFile";
import type { RouteSegmentFile } from "@/lib/pdr/airwayDirection";

/**
 * Round-trip: a real server download export (GeoJSON / CSV) must re-import with
 * its full 4D trajectory preserved — so a post-CD&R-fix download, re-uploaded,
 * shows the SAVED path (no regeneration). Fixtures are generated by the backend
 * (`/api/generate` → `/api/download/{key}.{ext}`).
 */
function fixture(name: string): string {
  return readFileSync(
    fileURLToPath(new URL(`./__fixtures__/${name}`, import.meta.url)),
    "utf-8",
  );
}

const ISO = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/;

describe("parseFlightFile — trajectory round-trip", () => {
  it("recovers full points + route from a GeoJSON download", async () => {
    const text = fixture("sample_download.geojson");
    const file = new File([text], "sample_download.geojson");
    const recs = await parseFlightFile(file);

    expect(recs).toHaveLength(1);
    const r = recs[0];
    expect(r.callsign).toBe("RT1");
    expect(r.adep).toBe("VTBD");
    expect(r.ades).toBe("VTUD");
    expect(r.route).toBe("NOBER W21 SURGU");

    // The whole flown path is carried through for an as-is load.
    expect(r.trajectory).toBeDefined();
    expect(r.trajectory!.points.length).toBeGreaterThan(100);
    // Timestamps normalised to strict ISO (space → T) and monotonic.
    const ts = r.trajectory!.points.map((p) => p.epoch_ts);
    expect(ISO.test(ts[0])).toBe(true);
    for (let i = 1; i < ts.length; i++) {
      expect(new Date(ts[i]).getTime()).toBeGreaterThanOrEqual(
        new Date(ts[i - 1]).getTime(),
      );
    }
    // Real altitudes + a climb→cruise phase progression survive.
    const alts = r.trajectory!.points.map((p) => p.altitude_ft ?? 0);
    expect(Math.max(...alts)).toBeGreaterThan(30000);
    expect(new Set(r.trajectory!.points.map((p) => p.phase)).size).toBeGreaterThan(1);
    // Route waypoints recovered from the `waypoint` marker column (so the
    // re-imported summary lists the same fixes as when generated).
    expect(r.trajectory!.route.length).toBeGreaterThan(1);
    const idents = r.trajectory!.route.map((w) => w.ident);
    expect(idents).toContain("NOBER");
    expect(idents).toContain("SURGU");
    // Each recovered waypoint sits on the flown path (has finite coords).
    for (const w of r.trajectory!.route) {
      expect(Number.isFinite(w.lat) && Number.isFinite(w.lon)).toBe(true);
    }
  });

  it("recovers full points from a CSV download", async () => {
    const text = fixture("sample_download.csv");
    const file = new File([text], "sample_download.csv");
    const recs = await parseFlightFile(file);

    expect(recs).toHaveLength(1);
    const r = recs[0];
    expect(r.callsign).toBe("RT1");
    expect(r.trajectory).toBeDefined();
    expect(r.trajectory!.points.length).toBeGreaterThan(100);
    expect(ISO.test(r.trajectory!.points[0].epoch_ts)).toBe(true);
    expect(
      Math.max(...r.trajectory!.points.map((p) => p.altitude_ft ?? 0)),
    ).toBeGreaterThan(30000);
    // The Waypoint column is recovered into the route (CSV has no LineString).
    const idents = r.trajectory!.route.map((w) => w.ident);
    expect(idents).toContain("NOBER");
    expect(idents).toContain("SURGU");
  });
});

/**
 * A track re-filed as an FPL (e.g. `make_cat062_fpl.py`'s VY sibling) carries
 * only the crossing fixes it was seen at — dep/dest/acid/wp1../wp3, no route
 * string, no SID/STAR, no airport it can offer a filed plan for. Without this,
 * every such row lands in the panel with "Enter an Item-15 route string" and
 * can never generate.
 */
describe("parseFlightFile — bare waypoint columns (no route string)", () => {
  const csv = [
    "dep,dest,acid,actype,rfl,dof,time,entry_fl,wp1,wp2,wp3",
    "VHHH,OBBI,BCS547,A333,340,20250603,0007,340,AKSAG,MDY,APAGO",
  ].join("\n");

  // `fetchRouteSegments` (imported by flightFile.ts) memoises its result in a
  // module-level variable, so each case here resets the module registry and
  // re-imports fresh — otherwise the first case's fetch outcome would leak
  // into the second regardless of how `fetch` is stubbed for it.
  afterEach(() => {
    vi.unstubAllGlobals();
    vi.resetModules();
  });

  it("builds a DCT-joined route from wp1/wp2/wp3 when the segment table is unreachable", async () => {
    vi.stubGlobal(
      "fetch",
      vi.fn().mockRejectedValue(new Error("network down")),
    );
    const { parseFlightFile: parse } = await import("@/lib/flightFile");

    const file = new File([csv], "track.csv");
    const recs = await parse(file);

    expect(recs).toHaveLength(1);
    const r = recs[0];
    expect(r.callsign).toBe("BCS547");
    expect(r.adep).toBe("VHHH");
    expect(r.ades).toBe("OBBI");
    expect(r.rfl).toBe(340);
    expect(r.route).toBe("DCT AKSAG DCT MDY DCT APAGO DCT");
    // No combined eobt/etd/departure_time column — built from dof + time.
    expect(r.eobt).toBe("2025-06-03T00:07");
  });

  it("leaves eobt undefined when dof or time is missing or malformed", async () => {
    vi.stubGlobal("fetch", vi.fn().mockRejectedValue(new Error("network down")));
    const { parseFlightFile: parse } = await import("@/lib/flightFile");

    const noTime = [
      "dep,dest,acid,actype,rfl,dof,wp1",
      "VHHH,OBBI,BCS547,A333,340,20250603,AKSAG",
    ].join("\n");
    const recs = await parse(new File([noTime], "track.csv"));
    expect(recs[0].eobt).toBeUndefined();
  });

  it("labels a span with its real ATS route designator when the published segment table joins the two fixes", async () => {
    const segments: RouteSegmentFile = {
      source: "test",
      validFrom: "",
      validTo: "",
      segments: [
        {
          route: "A599",
          from: "AKSAG",
          to: "MDY",
          direction: "BOTH",
          lowerFt: null,
          upperFt: null,
          lengthNm: null,
        },
        // MDY-APAGO is deliberately absent: that span should stay DCT.
      ],
    };
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({ ok: true, json: async () => segments }),
    );
    const { parseFlightFile: parse } = await import("@/lib/flightFile");

    const file = new File([csv], "track.csv");
    const recs = await parse(file);

    expect(recs[0].route).toBe("AKSAG A599 MDY DCT APAGO");
  });
});

describe("parseFlightFile — entry_fl (transit level)", () => {
  it("reads entry_fl as the transit level, and treats 0 as 'from the ground'", async () => {
    vi.stubGlobal("fetch", vi.fn().mockRejectedValue(new Error("network down")));
    const { parseFlightFile: parse } = await import("@/lib/flightFile");
    const csv = [
      "dep,dest,acid,actype,rfl,dof,time,entry_fl,wp1,wp2",
      "OERK,ZSPD,CES270,A332,350,20250603,0002,350,CHILA,LSO",
      "VYMD,VYTL,UBZ1226,AT76,0,20250603,0100,0,VYMD,VYTL",
    ].join("\n");
    const recs = await parse(new File([csv], "track.csv"));
    expect(recs[0].entryFl).toBe(350);
    expect(recs[1].entryFl).toBeUndefined();
    vi.unstubAllGlobals();
    vi.resetModules();
  });
});
