#!/usr/bin/env python3
"""Generate a fully synthetic flight dataset for the flight playback viewer.

Run:  python3 generate_synthetic_traffic.py
Writes synthetic_traffic_sample.csv next to this script, ready to load through
the viewer's CSV tab. Edit the FLIGHTS table at the bottom to model your own
traffic; the sampler handles the geometry.

No real surveillance data: every callsign and operator is fabricated. Aerodrome
ICAO codes and VTBS runway thresholds are real (public AIP data) so the
movement filters, the runway/AMAN panel and the holding detector behave the way
they do in production.

Flights are built as a polyline of waypoints (lat, lon, altitude, IAS) and then
walked at a fixed sample interval, which lets finals, departures and holding
racetracks all be generated by the same sampler.
"""
import csv
import math
from datetime import datetime, timedelta, timezone

STEP_S = 15
CLIP_NM = 190.0   # tracks enter/leave the window this far from VTBS
T0 = datetime(2026, 3, 4, 2, 0, 0, tzinfo=timezone.utc)
NM = 1852.0
R_EARTH = 6371000.0

# Real VTBS thresholds (public AIP): (lat, lon, true bearing of the landing run)
VTBS_RWY = {
    "19":  (13.69171389, 100.76103333, 194.326),
    "20L": (13.70366944, 100.74317778, 194.327),
    "20R": (13.70018889, 100.73844722, 194.327),
}

# Overflight transits: acid -> (entry point, exit point). Route pairs chosen
# because they really do cross the Bangkok FIR; the crossing is given
# explicitly rather than derived from a full origin-destination great circle.
OVERFLY = {
    "SYN730": ((15.20, 96.30), (16.20, 105.60)),   # OMDB -> VHHH, westbound entry
    "SYN744": ((16.05, 105.60), (14.95, 96.30)),   # VHHH -> OMDB, reciprocal
    "SYN751": ((14.00, 96.50), (7.50, 100.20)),    # VIDP -> WSSS, diagonal
}

AERODROMES = {
    "VTBS": (13.6811, 100.7472), "VTBD": (13.9126, 100.6068),
    "VTCC": (18.7669, 98.9626),  "VTSP": (8.1132, 98.3169),
    "VTUU": (15.2513, 104.8703), "VTSS": (6.9333, 100.3925),
    "VTBU": (12.6799, 101.0050), "VTCT": (19.9525, 99.8829),
    "WSSS": (1.3592, 103.9894),  "VVNB": (21.2212, 105.8072),
    "VHHH": (22.3089, 113.9147), "WMKK": (2.7456, 101.7099),
    "VDPP": (11.5466, 104.8441), "RJBB": (34.4342, 135.2330),
    "OMDB": (25.2528, 55.3644),  "VIDP": (28.5665, 77.1031),
}


def dist_nm(a, b):
    p1, p2 = math.radians(a[0]), math.radians(b[0])
    dl = math.radians(b[1] - a[1])
    d = 2 * math.asin(math.sqrt(
        math.sin((p2 - p1) / 2) ** 2
        + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2))
    return d * R_EARTH / NM


def bearing(a, b):
    p1, p2 = math.radians(a[0]), math.radians(b[0])
    dl = math.radians(b[1] - a[1])
    y = math.sin(dl) * math.cos(p2)
    x = math.cos(p1) * math.sin(p2) - math.sin(p1) * math.cos(p2) * math.cos(dl)
    return (math.degrees(math.atan2(y, x)) + 360) % 360


def dest_point(origin, brg_deg, d_nm):
    p1, l1 = math.radians(origin[0]), math.radians(origin[1])
    brg, dr = math.radians(brg_deg), (d_nm * NM) / R_EARTH
    p2 = math.asin(math.sin(p1) * math.cos(dr) + math.cos(p1) * math.sin(dr) * math.cos(brg))
    l2 = l1 + math.atan2(math.sin(brg) * math.sin(dr) * math.cos(p1),
                         math.cos(dr) - math.sin(p1) * math.sin(p2))
    return math.degrees(p2), math.degrees(l2)


def gc_interp(a, b, frac):
    p1, l1, p2, l2 = map(math.radians, (a[0], a[1], b[0], b[1]))
    d = 2 * math.asin(math.sqrt(
        math.sin((p2 - p1) / 2) ** 2
        + math.cos(p1) * math.cos(p2) * math.sin((l2 - l1) / 2) ** 2))
    if d == 0:
        return a
    x_ = math.sin((1 - frac) * d) / math.sin(d)
    y_ = math.sin(frac * d) / math.sin(d)
    x = x_ * math.cos(p1) * math.cos(l1) + y_ * math.cos(p2) * math.cos(l2)
    y = x_ * math.cos(p1) * math.sin(l1) + y_ * math.cos(p2) * math.sin(l2)
    z = x_ * math.sin(p1) + y_ * math.sin(p2)
    return math.degrees(math.atan2(z, math.hypot(x, y))), math.degrees(math.atan2(y, x))


def densify(a, b, alt_a, alt_b, ias_a, ias_b, step_nm=8.0):
    """Break a long leg into great-circle waypoints so tracks follow a GC path."""
    d = dist_nm(a, b)
    if d <= step_nm:
        return [(b[0], b[1], alt_b, ias_b)]
    out = []
    k = int(math.ceil(d / step_nm))
    for i in range(1, k + 1):
        f = i / k
        lat, lon = gc_interp(a, b, f)
        out.append((lat, lon, alt_a + (alt_b - alt_a) * f, ias_a + (ias_b - ias_a) * f))
    return out


def final_approach(rwy, from_nm=14.0, gs_deg=3.0):
    """Waypoints down the extended centreline to the threshold, then a rollout."""
    lat, lon, brg = VTBS_RWY[rwy]
    thr = (lat, lon)
    out, back = [], (brg + 180) % 360
    d = from_nm
    while d > 0.05:
        p = dest_point(thr, back, d)
        alt = d * 6076.0 * math.tan(math.radians(gs_deg))
        ias = 160 + min(d, 12) * 4          # 208 kt at 12 NM down to 160 kt at the threshold
        out.append((p[0], p[1], alt, ias))
        d -= 0.5
    out.append((thr[0], thr[1], 0.0, 145))                       # touchdown
    for r in (0.4, 0.9, 1.5, 2.0):                               # landing roll
        p = dest_point(thr, brg, r)
        out.append((p[0], p[1], 0.0, max(140 - r * 60, 12)))
    return out


def departure(rwy, to_nm=14.0):
    """Takeoff roll from the threshold, then a climb out along the centreline."""
    lat, lon, brg = VTBS_RWY[rwy]
    thr = (lat, lon)
    out = [(thr[0], thr[1], 0.0, 10)]
    for r, ias in ((0.5, 80), (1.2, 140), (1.9, 165)):           # roll, then rotate
        p = dest_point(thr, brg, r)
        out.append((p[0], p[1], 0.0, ias))
    d = 2.4
    while d <= to_nm:
        p = dest_point(thr, brg, d)
        out.append((p[0], p[1], (d - 1.9) * 460, 175 + min(d, 12) * 6))
        d += 0.6
    return out


def holding(centre, inbound_brg, alt_ft, ias, laps=3, leg_s=60, right=True):
    """A standard racetrack hold: 1-minute legs, rate-one 180 degree turns."""
    leg_nm = ias * (leg_s / 3600.0)
    radius = leg_nm / math.pi                 # 180 deg covered in the same leg time
    out = []
    fix = centre
    for _ in range(laps):
        # Inbound leg to the fix.
        start = dest_point(fix, (inbound_brg + 180) % 360, leg_nm)
        for i in range(1, 9):
            p = gc_interp(start, fix, i / 8)
            out.append((p[0], p[1], alt_ft, ias))
        # Turn at the fix through 180 degrees onto the outbound leg.
        turn_c = dest_point(fix, (inbound_brg + (90 if right else -90)) % 360, radius)
        a0 = bearing(turn_c, fix)
        for i in range(1, 13):
            ang = a0 + (180 if right else -180) * (i / 12)
            p = dest_point(turn_c, ang % 360, radius)
            out.append((p[0], p[1], alt_ft, ias))
        # Outbound leg.
        ob_start = out[-1][:2]
        ob_end = dest_point(ob_start, inbound_brg % 360 + 180, leg_nm)
        for i in range(1, 9):
            p = gc_interp(ob_start, ob_end, i / 8)
            out.append((p[0], p[1], alt_ft, ias))
        # Turn back inbound.
        turn_c2 = dest_point(ob_end, ((inbound_brg + 180) + (90 if right else -90)) % 360, radius)
        a1 = bearing(turn_c2, ob_end)
        for i in range(1, 13):
            ang = a1 + (180 if right else -180) * (i / 12)
            p = dest_point(turn_c2, ang % 360, radius)
            out.append((p[0], p[1], alt_ft, ias))
    return out


def walk(wps, start_time):
    """Sample a waypoint polyline at STEP_S using each leg's IAS."""
    rows, t, i = [], 0.0, 0
    cur = wps[0]
    pos, alt, ias = (cur[0], cur[1]), cur[2], cur[3]
    out = [(pos, alt, ias, 0.0)]
    while i < len(wps) - 1:
        nxt = wps[i + 1]
        seg_len = dist_nm(pos, (nxt[0], nxt[1]))
        spd = max((ias + nxt[3]) / 2, 12)
        step_nm = spd * (STEP_S / 3600.0)
        if seg_len <= step_nm or seg_len < 1e-6:
            t += (seg_len / max(spd, 1)) * 3600.0
            pos, alt, ias = (nxt[0], nxt[1]), nxt[2], nxt[3]
            i += 1
            out.append((pos, alt, ias, t))
            continue
        f = step_nm / seg_len
        lat, lon = gc_interp(pos, (nxt[0], nxt[1]), f)
        alt += (nxt[2] - alt) * f
        ias += (nxt[3] - ias) * f
        pos = (lat, lon)
        t += STEP_S
        out.append((pos, alt, ias, t))
    # Resample onto an exact STEP_S grid.
    rows = []
    total = out[-1][3]
    k = 0
    for s in range(0, int(total) + 1, STEP_S):
        while k < len(out) - 2 and out[k + 1][3] < s:
            k += 1
        a, b = out[k], out[min(k + 1, len(out) - 1)]
        span = max(b[3] - a[3], 1e-6)
        f = min(max((s - a[3]) / span, 0.0), 1.0)
        lat, lon = gc_interp(a[0], b[0], f)
        alt = a[1] + (b[1] - a[1]) * f
        ias = a[2] + (b[2] - a[2]) * f
        nlat, nlon = gc_interp(a[0], b[0], min(f + 0.08, 1.0))
        hdg = bearing((lat, lon), (nlat, nlon)) if (nlat, nlon) != (lat, lon) else 0.0
        rows.append((start_time + timedelta(seconds=s), lat, lon, alt, ias, hdg))
    return rows


# (acid, actype, dep, dest, kind, cruise_fl, start_min, rwy)
FLIGHTS = [
    # VTBS arrivals with a runway-aligned final -> populate the Runway/AMAN panel.
    ("DEM108", "A321", "VTCC", "VTBS", "arr", 330, 2, "19"),
    ("SMP317", "A333", "WSSS", "VTBS", "arr", 370, 9, "20L"),
    ("SMP409", "B789", "VHHH", "VTBS", "arr", 390, 15, "19"),
    ("EXA879", "B38M", "VTCT", "VTBS", "arr", 320, 22, "20L"),
    ("MOC912", "E190", "VDPP", "VTBS", "arr", 300, 29, "19"),
    ("DEM231", "B738", "VTSP", "VTBS", "arr", 350, 36, "20L"),
    ("EXA867", "A20N", "VTBU", "VTBS", "arr", 200, 43, "19"),
    # A hold north of VTBS before the approach -> populates the Holding panel.
    ("SMP512", "A320", "VTUU", "VTBS", "hold", 110, 5, "19"),
    # VTBS departures off 20R.
    ("DEM101", "A320", "VTBS", "VTCC", "dep", 330, 3, "20R"),
    ("DEM224", "B738", "VTBS", "VTSP", "dep", 350, 11, "20R"),
    ("SMP310", "A333", "VTBS", "WSSS", "dep", 370, 18, "20R"),
    ("SMP402", "B789", "VTBS", "VHHH", "dep", 390, 25, "20R"),
    ("EXA872", "B38M", "VTBS", "VTCT", "dep", 320, 32, "20R"),
    ("MOC905", "E190", "VTBS", "VDPP", "dep", 300, 39, "20R"),
    ("MOC933", "A332", "VTBS", "VVNB", "dep", 350, 46, "20R"),
    ("SMP428", "B788", "VTBS", "WMKK", "dep", 360, 53, "20R"),
    # Domestic pairs not touching VTBS.
    ("TST515", "A320", "VTBD", "VTUU", "dom", 280, 8, None),
    ("TST522", "A320", "VTUU", "VTBD", "dom", 280, 31, None),
    ("TST618", "AT76", "VTBD", "VTSS", "dom", 230, 20, None),
    ("TST625", "AT76", "VTSS", "VTBD", "dom", 230, 42, None),
    ("DEM145", "A320", "VTBD", "VTCC", "dom", 290, 55, None),
    ("TST537", "A319", "VTCC", "VTBD", "dom", 270, 62, None),
    # Overflies through the Bangkok FIR.
    ("SYN730", "B77W", "OMDB", "VHHH", "ovf", 400, 1, None),
    ("SYN744", "A359", "VHHH", "OMDB", "ovf", 380, 13, None),
    ("SYN751", "B744", "VIDP", "WSSS", "ovf", 360, 27, None),
]

rows_out = []
for f in FLIGHTS:
    acid, actype, dep, dest, kind, cruise_fl, start_min, rwy = f
    a, b = AERODROMES[dep], AERODROMES[dest]
    cruise_ft = cruise_fl * 100.0
    wps = []

    if kind == "arr":
        iaf = dest_point((VTBS_RWY[rwy][0], VTBS_RWY[rwy][1]),
                         (VTBS_RWY[rwy][2] + 180) % 360, 14.0)
        tot = dist_nm(a, iaf)
        if tot > CLIP_NM:                                        # already airborne
            entry = gc_interp(a, iaf, (tot - CLIP_NM) / tot)
            wps = [(entry[0], entry[1], cruise_ft, 300)]
            wps += densify(entry, iaf, cruise_ft, cruise_ft, 300, 300, 25)
        else:
            wps = [(a[0], a[1], 0.0, 250)]
            wps += densify(a, iaf, 0.0, cruise_ft, 250, 300, 25)
        wps += final_approach(rwy)
    elif kind == "hold":
        hold_ctr = dest_point((VTBS_RWY["19"][0], VTBS_RWY["19"][1]), 14.326, 46.0)
        tot_h = dist_nm(a, hold_ctr)
        if tot_h > 90:
            entry = gc_interp(a, hold_ctr, (tot_h - 90) / tot_h)
            wps = [(entry[0], entry[1], cruise_ft, 250)]
            wps += densify(entry, hold_ctr, cruise_ft, cruise_ft, 250, 250, 20)
        else:
            wps = [(a[0], a[1], 0.0, 240)]
            wps += densify(a, hold_ctr, 0.0, cruise_ft, 240, 250, 20)
        wps += holding(hold_ctr, 194.326, cruise_ft, 235, laps=3)
        iaf = dest_point((VTBS_RWY[rwy][0], VTBS_RWY[rwy][1]),
                         (VTBS_RWY[rwy][2] + 180) % 360, 14.0)
        wps += densify(wps[-1][:2], iaf, cruise_ft, 4400, 235, 208, 6)
        wps += final_approach(rwy)
    elif kind == "dep":
        wps = departure(rwy)
        head = wps[-1]
        tot = dist_nm(head[:2], b)
        exit_pt = gc_interp(head[:2], b, min(CLIP_NM / tot, 1.0)) if tot > CLIP_NM else b
        wps += densify(head[:2], exit_pt, head[2], cruise_ft, head[3], 310, 25)
    elif kind == "dom":
        mid = gc_interp(a, b, 0.5)
        wps = [(a[0], a[1], 0.0, 200)]
        wps += densify(a, mid, 0.0, cruise_ft, 200, 290, 20)
        wps += densify(mid, b, cruise_ft, 0.0, 290, 180, 20)
    else:  # overflight: level throughout, only the FIR transit is in the window
        p0, p1 = OVERFLY[acid]
        wps = [(p0[0], p0[1], cruise_ft, 320)]
        wps += densify(p0, p1, cruise_ft, cruise_ft, 320, 320, 25)

    start = T0 + timedelta(minutes=start_min)
    key = f"{acid}_{dep}_{dest}_{start:%Y-%m-%d %H:%M}"
    prev_alt = None
    for ts, lat, lon, alt, ias, hdg in walk(wps, start):
        if prev_alt is None:
            vert, rate = 0, 0
        else:
            dft = alt - prev_alt
            rate = int(dft / (STEP_S / 60.0))
            vert = 1 if rate > 300 else (2 if rate < -300 else 0)
        prev_alt = alt
        rows_out.append({
            "flight_key": key,
            "latitude": round(lat, 5), "longitude": round(lon, 5),
            "timestamp_utc": ts.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "flight_level": round(alt / 100.0, 1),
            "acid": acid, "actype": actype, "dep": dep, "dest": dest,
            "ias_dap": int(round(ias)), "mag_heading_dap": int(round(hdg)),
            "rate_cd": rate, "vert": vert,
        })

out = "synthetic_traffic_sample.csv"
cols = ["flight_key", "latitude", "longitude", "timestamp_utc", "flight_level",
        "acid", "actype", "dep", "dest", "ias_dap", "mag_heading_dap",
        "rate_cd", "vert"]
with open(out, "w", newline="") as fh:
    w = csv.DictWriter(fh, fieldnames=cols)
    w.writeheader()
    w.writerows(rows_out)

keys = {r["flight_key"] for r in rows_out}
print(f"{len(rows_out)} rows, {len(keys)} flights -> {out}")
